### ISSUE TITLE
Remote server troubles with .boxr-oauth

### ISSUE THREAD

**Issue by johnschoofs** [brendan-r/boxr#60] opened 2017-09-11 18:38 UTC
Hi there,

I know you said this is unsupported in your documentation, but I figured it might be worth reaching out anyways.  I've copied this file to an equivalent directory (/home/user) on my server and am going to retrieve a file and am getting: 

Error in checkAuth() : 
  It doesn't look like you've set up authentication for boxr yet. 

Any help would be appreciated.  Thanks in advance! 

John

**Comment by johnschoofs** [comment] 2017-09-11 20:22
One more item to add - I've followed the steps in the feature request for rstudio server and haven't had any luck.  Still getting the error message.

**Comment by skirmer** [comment] 2017-09-13 21:34
I am seeing a similar issue - on an account where the .boxr-oauth worked beautifully in my remote environment until about 12 hours ago. It just stopped acknowledging my oauth token today. Any advice? I had a colleague replicate the same problem, and he had also previously had success with it.

**Comment by johnschoofs** [comment] 2017-09-13 23:10
Hi @skirmer - I came up with a fix that actually seems to work pretty well (still testing).  I wrote a little shell script that mirrors the files I need using lftp.  In my case we're not talking about massive data transfers, but even so, I would assume this approach to work, just need to modify how mirroring works and frequency of job.  You can then work with the files locally, on your server.  

lmk if this idea seems good to you but may need clarification or have questions.

**Comment by skirmer** [comment] 2017-09-14 15:02
Well, I need a certain level of security for the files, so I'm not sure. I am working on a straight FTP to box solution, which seems like it might do the job, but it's more convoluted than boxr so I was hoping the oauth situation could be solved. Tell me about your strategy though, it might do!

**Comment by johnschoofs** [comment] 2017-09-14 19:48
If you're doing a straight ftp to box, this will work I believe.  I'm on a vm using Ubuntu 16.04 LTS.  

1. apt-get lftp (if you don't have it installed already)
2. make sure you're at the working directory you'd like to put the files you receive from box or push to box
3. authenticate using lftp -u username,password ftp.box.com
4. give other instructions as your use case dictates using lftp -e 'mirror; bye;' (small example)
5. deal with permissions issues as needed
6. ingest & perform some operations in R.  

Hope this is helpful!

**Comment by brendan-r** [comment] 2017-09-18 03:20
Dear both, I'm afraid this is the reason I call this out as not working is because it doesn't work, as per #23.

This is really an issue with OAuth2.0 tokens, as opposed to anything peculiar to this package. They expire after a while, by design, requiring a login via a browser on the machine that's making the API requests. I'm afraid there's not much I can do to help.

If you're very keen on trying a solution that isn't moving tokens around, there may be something in this [post from Rstudio](https://github.com/brendan-r/boxr/issues/23) (untested).

Sorry I can't be more help.

**Closed by brendan-r** 2017-09-18 03:20 UTC
